vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        users_images:
           uri_prefix: '%app.path.users_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           upload_destination: '%kernel.project_dir%/public%app.path.users_images%'
    
        cars_images:
           uri_prefix: '%app.path.cars_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           upload_destination: '%kernel.project_dir%/public%app.path.cars_images%'
